-- Schéma initial KAOM · Beauty of Sahel (compatible PostgreSQL et H2 en mode PostgreSQL)

create table collections (
    id            bigint generated by default as identity primary key,
    slug          varchar(120)  not null unique,
    name          varchar(120)  not null,
    season        varchar(120),
    tagline       varchar(300),
    description   varchar(2000),
    cover_url     varchar(500),
    motif         varchar(20)   not null default 'bazin',
    tone          varchar(20)   not null default 'sable',
    featured      boolean       not null default false,
    position      integer       not null default 0,
    published     boolean       not null default true,
    created_at    timestamp with time zone not null,
    updated_at    timestamp with time zone not null
);

create table products (
    id            bigint generated by default as identity primary key,
    slug          varchar(160)  not null unique,
    name          varchar(160)  not null,
    collection_id bigint references collections(id) on delete set null,
    category      varchar(30)   not null,
    gender        varchar(20)   not null,
    price         integer       not null,
    old_price     integer,
    fabric        varchar(300),
    description   varchar(4000),
    motif         varchar(20)   not null default 'bazin',
    tone          varchar(20)   not null default 'sable',
    badge         varchar(40),
    bestseller    boolean       not null default false,
    status        varchar(20)   not null,
    stock         integer       not null default 0,
    created_at    timestamp with time zone not null,
    updated_at    timestamp with time zone not null
);
create index idx_products_collection on products(collection_id);
create index idx_products_status on products(status);

create table product_sizes (
    product_id    bigint not null references products(id) on delete cascade,
    position      integer not null,
    size          varchar(30) not null,
    primary key (product_id, position)
);

create table product_colors (
    product_id    bigint not null references products(id) on delete cascade,
    position      integer not null,
    name          varchar(60) not null,
    hex           varchar(9)  not null,
    primary key (product_id, position)
);

create table product_images (
    id            bigint generated by default as identity primary key,
    product_id    bigint not null references products(id) on delete cascade,
    url           varchar(500) not null,
    alt           varchar(200),
    position      integer not null default 0
);
create index idx_images_product on product_images(product_id);

create table customer_requests (
    id            bigint generated by default as identity primary key,
    type          varchar(20)   not null,
    status        varchar(20)   not null,
    customer_name varchar(120)  not null,
    phone         varchar(40)   not null,
    email         varchar(160),
    message       varchar(2000),
    items         varchar(4000),
    total         integer       not null default 0,
    created_at    timestamp with time zone not null,
    updated_at    timestamp with time zone not null
);
create index idx_requests_status on customer_requests(status);

create table newsletter_subscribers (
    id            bigint generated by default as identity primary key,
    email         varchar(160) not null unique,
    created_at    timestamp with time zone not null
);

create table admin_users (
    id            bigint generated by default as identity primary key,
    email         varchar(160) not null unique,
    password_hash varchar(100) not null,
    display_name  varchar(120),
    created_at    timestamp with time zone not null
);
